name: Release resi sessiontest binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: sessiontest build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup go and release
        uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "resisessiontest"